name: Deploy infra

on:
  # pull_request:
  #   branches: [ "main" ] # Trigger on PR based on main branch.
  workflow_dispatch: # Allow manual triggering of the workflow.

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      # https://github.com/marketplace/actions/setup-aws-sam-cli
      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992887713340:role/TrustActionByGitHub
          aws-region: us-east-1

      - name: SAM build
        run: sam build --use-container

      - name: SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
